[project]
name = "websearch-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rajesh kumar", email = "rajeshxdatascience@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=4.0.5",
    "python-dotenv>=1.2.3",
]

[project.scripts]
websearch-mcp-server = "websearch_mcp_server:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
